baseURL: "https://medinas.org/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: My Personal Website
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-XHWQ5GN8QH

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        profileMode:
          enabled: true
          title: Luis Medinas
          subtitle: "📓Notes | 💻Setup | ℹ️ Information about me.<p>The opinions expressed here
           are my own and don't not reflect
           the position of my employer or any other party."
          imageUrl: "https://images.unsplash.com/photo-1664977250570-5c399ec4244b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2038&q=80"
          imageTitle: my image
          imageWidth: 150
          imageHeight: 150
          buttons:
            - name: Posts
              url: posts
            - name: About
              url: about
            - name: New Tab
              url: newtab/

        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 2
                - name: Tags
                  url: tags/
                  weight: 6
                - name: Setup
                  url: mysetup/
                  weight: 4
                - name: New Tab
                  url: newtab/
                  weight: 3
                - name: About
                  url: about/
                  weight: 1

    pt:
        languageName: ":pt:"
        languageAltTitle: Portuguese
        weight: 2
        title: O meu Site pessoal 
        taxonomies:
          category: PTcategories
          tag: PTtags
          series: PTseries
        profileMode:
            enabled: true
            title: Luis Medinas
            imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
            imageTitle: ProfileMode image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "🇵🇹 Versão Portuguesa | 🚧 Em construção"
            buttons:
                - name: Blog
                  url: posts
        menu:
            main:
                - name: Arquivos
                  url: archives/
                  weight: 5
                - name: PTTags
                  url: pttags
                  weight: 10
                - name: PTCategories
                  url: ptcategories
                  weight: 10
                - name: PTSeries
                  url: ptseries
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "My Personal Website"
    author: Luis Medinas
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    ShowFullTextinRSS: true
    ShareButtons: ["twitter", "reddit", "facebook", "whatsapp", "linkedin"]
    comments: false
    images: ["papermod-cover.png"]

    homeInfoParams:
        Title: "Website"
        Content: >
            Welcome to my personal Website.

            - Notes
            - Blog
            - About
            - Contacts
            - Setup

            The opinions expressed here
            are my own and don't not reflect
            the position of my employer or any other party.

    socialIcons:
        - name: github
          url: "https://github.com/lmedinas"
        - name: Twitter
          url: "https://www.twitter.com/lmedinas"
        - name: Mastodon
          url: "https://mastodon.social/@NexusM"
        - name: Instagram
          url: "https://www.instagram.com/lmedinas"
        - name: LinkedIn
          url: "https://linkedin.com/in/lmedinas"
        - name: Rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/lmedinas/websitelm/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    #analytics:
    #     google:
    #         SiteVerificationTag: "G-XHWQ5GN8QH"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
